// Generated by CoffeeScript 1.12.7
(function() {
  var http, server;

  http = require('http');

  server = require('./server');

  http.createServer(server.logic).listen(server.port, server.address);

}).call(this);
