// Generated by CoffeeScript 1.12.7
(function() {
  var fs, renderResource, renderer, url;

  fs = require('fs');

  url = require('url');

  renderer = require('./renderer');

  renderResource = function(filename, type, res, callback) {
    var content;
    if (fs.existsSync("public/" + type + "/" + filename)) {
      return content = renderer.render(filename, type).then(function(content) {
        res.writeHead(200);
        res.write(content);
        return res.end();
      });
    } else {
      res.writeHead(404, {
        'Content-Type': "text/" + type
      });
      res.write('File not found');
      return res.end();
    }
  };

  module.exports = {
    logic: function(req, res) {
      var _, directory, error, filename, filetype, ref;
      try {
        url = url.parse(req.url);
        ref = url.pathname.split("/"), _ = ref[0], directory = ref[1], filetype = ref[2], filename = ref[3];
        if (directory === "") {
          directory = "/";
        }
        switch (directory) {
          case "/":
            return renderResource("index.pug", "pug", res);
          case "page1":
            return renderResource("articles/page1.pug", "pug", res);
          case "page2":
            return renderResource("articles/page2.pug", "pug", res);
          case "page3":
            return renderResource("articles/page3.pug", "pug", res);
          case "public":
            return renderResource(filename, filetype, res);
          default:
            res.writeHead(404, {
              'Content-Type': 'text/plain'
            });
            return res.end("Error 404: not found");
        }
      } catch (error1) {
        error = error1;
        res.writeHead(500, {
          'Content-Type': 'text/plain'
        });
        return res.end("Oops");
      }
    },
    port: "8888",
    address: "127.0.0.1"
  };

}).call(this);
